---
title: "Cognitive Styles Scoring"
format: html
theme: lumen
---

### necessary libraries and functions

```{r, eval=FALSE}

library("dplyr")

source("scoringFuns.R")

```


## Tolerance of Ambiguity

```{r}
#first we specify cols to be reverse coded

at_rev <- c("01", "02", "03",  "04", "05", "06", "09", "11", "12")

at_cols_rev <- paste0("at_", at_rev)

at_cols <- colnames(df %>%
  select(starts_with("at_")) %>%
  select(-ends_with((at_rev))))

# code!

df1 <- funScore(df, at_cols, "agreement", FALSE)
df2 <- funScore(df1, at_cols_rev, "agreement", TRUE)

```

## Thinking Style

Thinking style variables are coded as correct or incorrect

## Non-verbal Reasoning 

Non-verbal uses a unique scoring scheme

## Moralisation of Rationality

Moralisation of Rationality items use the standard scoring scheme so we can use the funScore function

```{r}

# no reverse coding

mor_cols <- colnames(df %>%
  select(starts_with("mor_")))

# code!

df1 <- funScore(df, mor_cols, "agreement", FALSE)


```

## Importance of Rationality

```{r}

# no reverse coding

imp_cols <- colnames(df %>%
  select(starts_with("imp_")))

# code!

df1 <- funScore(df, imp_cols, "agreement", FALSE)


```