---
title: "Morals/Values Scoring"
format: html
theme: lumen
---

### necessary libraries and functions

```{r, eval=FALSE}

library("dplyr")

source("scoringFuns.R")


```

## Individualism and Collectivism

As this uses our standard response scale for agreement we can use our standard scoring function

```{r}

#no items are reversed scored so we can just use the same function across all the ic items

#first we selct the relavent columns

ic_cols <- colnames(df %>%
  select(starts_with("ic_")))

# now we run the function

df <- funScore(df, ic_cols, "agreement", FALSE)

```

## Rebelliousness

Rebelliousness uses our standard extent coding scheme, which has its own function

```{r}

#there are no reverse coded items so we select all rebelliousness columns

reb_cols <- colnames(df %>%
  select(starts_with("reb_")))


df <- funScore(df, reb_cols, "extent", FALSE)
```


## Individual Choice Norms

```{r, eval=FALSE}

#there are no reverse coded items so we select all choice norms columns

icn_cols <- colnames(df %>%
  select(starts_with("icn_")))


df <- funScore(df, icn_cols, "agreement", FALSE)
```
```
